test:
  - src/tests/**/*

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
  - src/stocktracer/**/*

documentation:
  - docs/**/*

workflow:
  - .github/workflows

dependencies:
  - poetry.lock
